SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS VENTAS;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS CLIENTE;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CLIENTE (
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(75) NOT NULL,
apellido VARCHAR(75) NOT NULL,
documento VARCHAR(11) NOT NULL,
fecha_nacimiento DATE NOT NULL
);



CREATE TABLE PRODUCTO (
id INT PRIMARY KEY AUTO_INCREMENT,
descripcion VARCHAR(150) NOT NULL,
codigo VARCHAR(50) NOT NULL,
stock int NOT NULL,
precio double NOT NULL
);



CREATE TABLE VENTAS (
id INT PRIMARY KEY AUTO_INCREMENT,
cliente_id INT,
creacion DATETIME,
producto VARCHAR(50),
precio_producto int,
precio_total_venta int,
FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id)
);
